name: 'Svelte to Github Pages'
author: 'StilosDesign'
description: 'This Action will build your svelte or any project front-end and deploy it to Github Pages'
branding:
  icon: 'play'  
  color: 'green'
inputs:
  username:
    description: 'Your username'
    required: true
  reposname:
    description: 'Your reposname'
    required: true
  repospage:
    description: 'Your repospage'
    required: true
  token:
    description: 'Your Github token'
    required: true  
  script:
    description: 'Your Script'
    required: true  
  buildfolder:
    description: 'Your Build Folder'
    required: true  

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.token }}
    GITHUB_USERNAME: ${{ inputs.username }}
    TARGET_REPO: ${{ inputs.username }}/${{ inputs.reposname }}
    TARGET_BRANCH: ${{ inputs.repospage }}
    BUILD_SCRIPT: ${{ inputs.script }}
    BUILD_DIR: ${{ inputs.buildfolder }}